/*   1:    */ import java.applet.Applet;
/*   2:    */ import java.applet.AppletContext;
/*   3:    */ import java.awt.BorderLayout;
/*   4:    */ import java.awt.Button;
/*   5:    */ import java.awt.Choice;
/*   6:    */ import java.awt.Color;
/*   7:    */ import java.awt.Component;
/*   8:    */ import java.awt.Container;
/*   9:    */ import java.awt.Font;
/*  10:    */ import java.awt.Frame;
/*  11:    */ import java.awt.GridBagConstraints;
/*  12:    */ import java.awt.GridBagLayout;
/*  13:    */ import java.awt.GridLayout;
/*  14:    */ import java.awt.Insets;
/*  15:    */ import java.awt.Label;
/*  16:    */ import java.awt.Panel;
/*  17:    */ import java.awt.TextComponent;
/*  18:    */ import java.awt.event.ActionEvent;
/*  19:    */ import java.awt.event.ActionListener;
/*  20:    */ import java.awt.event.ItemEvent;
/*  21:    */ import java.awt.event.ItemListener;
/*  22:    */ import java.awt.event.TextEvent;
/*  23:    */ import java.awt.event.TextListener;
/*  24:    */ import java.io.PrintStream;
/*  25:    */ import java.net.URL;
/*  26:    */ import java.util.EventObject;
/*  27:    */ 
/*  28:    */ public class BreastPanel
/*  29:    */   extends Panel
/*  30:    */   implements ItemListener, TextListener, ActionListener
/*  31:    */ {
/*  32:    */   private static final long serialVersionUID = 1L;
/*  33:    */   Applet owner;
/*  34:    */   String email;
/*  35: 10 */   boolean man1 = false;
/*  36: 11 */   boolean man2 = false;
/*  37: 12 */   boolean man3 = false;
/*  38: 13 */   boolean man4 = false;
/*  39: 14 */   boolean consistencyCheck = false;
/*  40:    */   String consistencyString;
/*  41: 16 */   BreastPatient thePatient = new BreastPatient();
/*  42: 17 */   Choice comorbidityList = new Choice();
/*  43: 18 */   Choice erStatusList = new Choice();
/*  44: 19 */   Choice tumorGradeList = new Choice();
/*  45: 20 */   Choice tumorSizeList = new Choice();
/*  46: 21 */   Choice positiveNodeList = new Choice();
/*  47: 22 */   Choice calculateForList = new Choice();
/*  48: 23 */   Choice setList = new Choice();
/*  49: 24 */   Choice setList2 = new Choice();
/*  50: 25 */   PositiveIntField ageField = new PositiveIntField();
/*  51: 26 */   PositiveIntField riskField = new PositiveIntField();
/*  52: 27 */   PositiveIntField hormField = new PositiveIntField();
/*  53: 28 */   PositiveIntField chemField = new PositiveIntField();
/*  54: 29 */   PositiveIntField combField = new PositiveIntField();
/*  55: 30 */   Label riskLabel = new Label("10 Year Risk:");
/*  56: 31 */   Label hormoLabel = new Label("Hormonal Therapy: ");
/*  57: 32 */   Label chemoLabel = new Label("Chemotherapy: ");
/*  58: 33 */   Label comboLabel = new Label("Combined Therapy: ");
/*  59: 34 */   Label patientLabel = new Label("Patient Information");
/*  60: 35 */   Label therapyLabel = new Label("Adjuvant Therapy Effectiveness");
/*  61: 36 */   Button printButton = new Button("Print Results PDF");
/*  62: 37 */   Button helpButton = new Button("Access Help and Clinical Evidence");
/*  63: 38 */   Button picsButton = new Button("Images for Consultations");
/*  64: 39 */   Button progButton = new Button("Prognostic");
/*  65: 40 */   BreastGraph graph = new BreastGraph(false);
/*  66: 41 */   boolean shown35Warning = false;
/*  67:    */   
/*  68:    */   public BreastPanel(Applet newOwner, String emailParameter)
/*  69:    */   {
/*  70: 44 */     super(new GridBagLayout());
/*  71: 45 */     this.owner = newOwner;
/*  72: 46 */     this.email = emailParameter;
/*  73: 47 */     setBackground(Color.white);
/*  74: 48 */     initializeFonts();
/*  75: 49 */     initializeChoices();
/*  76: 50 */     buildInterface();
/*  77: 51 */     initializeListeners();
/*  78: 52 */     initializeInterface();
/*  79: 53 */     validate();
/*  80: 54 */     if (this.consistencyCheck)
/*  81:    */     {
/*  82: 55 */       removeAll();
/*  83: 56 */       setLayout(new GridLayout(5, 1));
/*  84: 57 */       add(new Label("Consistency Error!"));
/*  85: 58 */       add(new Label("There seems to be a rare internal inconsistency in the calculations"));
/*  86: 59 */       add(new Label("generated by your machine. Please contact us to help resolve this issue"));
/*  87: 60 */       add(new Label("before using the information or printouts generated by this program."));
/*  88: 61 */       if (this.consistencyString != null) {
/*  89: 62 */         add(new Label(this.consistencyString));
/*  90:    */       }
/*  91:    */     }
/*  92:    */   }
/*  93:    */   
/*  94:    */   public void initializeChoices()
/*  95:    */   {
/*  96: 68 */     this.comorbidityList.add("Perfect Health");
/*  97: 69 */     this.comorbidityList.add("Minor Problems");
/*  98: 70 */     this.comorbidityList.add("Average for Age");
/*  99: 71 */     this.comorbidityList.add("Major Prob. (+10)");
/* 100: 72 */     this.comorbidityList.add("Major Prob. (+20)");
/* 101: 73 */     this.comorbidityList.add("Major Prob. (+30)");
/* 102:    */     
/* 103: 75 */     this.erStatusList.add("Undefined");
/* 104: 76 */     this.erStatusList.add("Positive");
/* 105: 77 */     this.erStatusList.add("Negative");
/* 106:    */     
/* 107: 79 */     this.tumorGradeList.add("Undefined");
/* 108: 80 */     this.tumorGradeList.add("Grade 1");
/* 109: 81 */     this.tumorGradeList.add("Grade 2");
/* 110: 82 */     this.tumorGradeList.add("Grade 3");
/* 111:    */     
/* 112: 84 */     this.tumorSizeList.add("0.1 - 1.0 cm");
/* 113: 85 */     this.tumorSizeList.add("1.1 - 2.0 cm");
/* 114: 86 */     this.tumorSizeList.add("2.1 - 3.0 cm");
/* 115: 87 */     this.tumorSizeList.add("3.1 - 5.0 cm");
/* 116: 88 */     this.tumorSizeList.add("> 5.0 cm");
/* 117:    */     
/* 118: 90 */     this.positiveNodeList.add("0");
/* 119: 91 */     this.positiveNodeList.add("1 - 3");
/* 120: 92 */     this.positiveNodeList.add("4 - 9");
/* 121: 93 */     this.positiveNodeList.add("> 9");
/* 122:    */     
/* 123: 95 */     this.calculateForList.add("Mortality");
/* 124: 96 */     this.calculateForList.add("Relapse");
/* 125:    */     
/* 126: 98 */     this.setList.add("CMF-Like (Overview 2000)");
/* 127: 99 */     this.setList.add("Anthra. (Overview 2000)");
/* 128:100 */     this.setList.add("1st Generation Regimens");
/* 129:101 */     this.setList.add("  CA*4, CMF, FE(50)C*6");
/* 130:102 */     this.setList.add("2nd Generation Regimens");
/* 131:103 */     this.setList.add("  Anthra >4 Cycles >2 agnts.");
/* 132:104 */     this.setList.add("  CA*4 then T*4");
/* 133:105 */     this.setList.add("3rd Generation Regimens");
/* 134:    */     
/* 135:107 */     this.setList2.add("Tamoxifen (Overview 2000)");
/* 136:108 */     this.setList2.add("Aromatase Inhibitor for 5 yrs");
/* 137:109 */     this.setList2.add("Tam for 2-3 yrs then AI for 2-3 yrs");
/* 138:110 */     this.setList2.add("Ovarian Ablation");
/* 139:111 */     this.setList2.add("Ov. Abl. + Tam (or other horm)");
/* 140:    */   }
/* 141:    */   
/* 142:    */   public void buildInterface()
/* 143:    */   {
/* 144:116 */     GridBagConstraints gbc = new GridBagConstraints();
/* 145:117 */     gbc.anchor = 17;
/* 146:118 */     gbc.fill = 0;
/* 147:119 */     gbc.weightx = 0.0D;gbc.weighty = 0.0D;
/* 148:120 */     gbc.insets = new Insets(1, 1, 1, 1);
/* 149:121 */     gbc.ipadx = 1;gbc.ipady = 1;
/* 150:122 */     gbc.gridheight = 1;gbc.gridwidth = 2;
/* 151:123 */     gbc.gridx = 1;gbc.gridy = 1;
/* 152:    */     
/* 153:125 */     Panel patientInfo = new Panel(new GridBagLayout());
/* 154:126 */     patientInfo.add(this.patientLabel, gbc);
/* 155:127 */     gbc.gridwidth = 1;
/* 156:128 */     gbc.gridy = 2;patientInfo.add(new Label("Age:"), gbc);
/* 157:129 */     gbc.gridy = 3;patientInfo.add(new Label("Comorbidity:"), gbc);
/* 158:130 */     gbc.gridy = 4;patientInfo.add(new Label("ER Status:"), gbc);
/* 159:131 */     gbc.gridy = 5;patientInfo.add(new Label("Tumor Grade:"), gbc);
/* 160:132 */     gbc.gridy = 6;patientInfo.add(new Label("Tumor Size:"), gbc);
/* 161:133 */     gbc.gridy = 7;patientInfo.add(new Label("Positive Nodes:"), gbc);
/* 162:134 */     gbc.gridy = 8;patientInfo.add(new Label("Calculate For:"), gbc);
/* 163:135 */     gbc.gridy = 9;patientInfo.add(this.riskLabel, gbc);
/* 164:136 */     gbc.gridy = 2;
/* 165:137 */     gbc.gridx = 2;patientInfo.add(this.ageField, gbc);
/* 166:138 */     gbc.gridy = 3;patientInfo.add(this.comorbidityList, gbc);
/* 167:139 */     gbc.gridy = 4;patientInfo.add(this.erStatusList, gbc);
/* 168:140 */     gbc.gridy = 5;patientInfo.add(this.tumorGradeList, gbc);
/* 169:141 */     gbc.gridy = 6;patientInfo.add(this.tumorSizeList, gbc);
/* 170:142 */     gbc.gridy = 7;patientInfo.add(this.positiveNodeList, gbc);
/* 171:143 */     gbc.gridy = 8;patientInfo.add(this.calculateForList, gbc);
/* 172:144 */     gbc.gridy = 9;
/* 173:145 */     Panel riskPanel = new Panel(new BorderLayout());
/* 174:146 */     riskPanel.add(this.riskField, "West");
/* 175:147 */     riskPanel.add(this.progButton, "Center");
/* 176:148 */     patientInfo.add(riskPanel, gbc);
/* 177:    */     
/* 178:150 */     Panel therapyInfo = new Panel(new GridBagLayout());
/* 179:151 */     Panel use2Panel = new Panel(new BorderLayout());
/* 180:152 */     use2Panel.add(new Label("Horm: "), "West");
/* 181:153 */     use2Panel.add(this.setList2, "Center");
/* 182:154 */     Panel usePanel = new Panel(new BorderLayout());
/* 183:155 */     usePanel.add(new Label("Chemo: "), "West");
/* 184:156 */     usePanel.add(this.setList, "Center");
/* 185:157 */     gbc.gridwidth = 2;gbc.gridy = 1;
/* 186:158 */     gbc.gridx = 1;therapyInfo.add(this.therapyLabel, gbc);
/* 187:159 */     gbc.gridy = 2;therapyInfo.add(use2Panel, gbc);
/* 188:160 */     gbc.gridy = 3;therapyInfo.add(usePanel, gbc);
/* 189:161 */     gbc.gridwidth = 1;
/* 190:162 */     gbc.gridy = 4;therapyInfo.add(this.hormoLabel, gbc);
/* 191:163 */     gbc.gridy = 5;therapyInfo.add(this.chemoLabel, gbc);
/* 192:164 */     gbc.gridy = 6;therapyInfo.add(this.comboLabel, gbc);
/* 193:165 */     gbc.gridy = 4;
/* 194:166 */     gbc.gridx = 2;therapyInfo.add(this.hormField, gbc);
/* 195:167 */     gbc.gridy = 5;therapyInfo.add(this.chemField, gbc);
/* 196:168 */     gbc.gridy = 6;therapyInfo.add(this.combField, gbc);
/* 197:169 */     gbc.gridx = 1;
/* 198:170 */     gbc.gridy = 1;
/* 199:171 */     gbc.anchor = 11;
/* 200:    */     
/* 201:173 */     Panel graphInfo = new Panel(new GridBagLayout());
/* 202:174 */     graphInfo.setBackground(Color.white);
/* 203:175 */     gbc.gridwidth = 2;
/* 204:176 */     graphInfo.add(this.graph, gbc);
/* 205:177 */     gbc.gridwidth = 1;
/* 206:178 */     gbc.fill = 2;
/* 207:179 */     gbc.gridy = 2;graphInfo.add(new Label(" "), gbc);
/* 208:180 */     gbc.gridy = 3;graphInfo.add(this.printButton, gbc);
/* 209:181 */     gbc.gridx += 1;graphInfo.add(this.helpButton, gbc);
/* 210:182 */     gbc.fill = 0;
/* 211:183 */     gbc.gridx -= 1;
/* 212:184 */     gbc.gridwidth = 2;
/* 213:185 */     gbc.gridy = 4;graphInfo.add(this.picsButton, gbc);
/* 214:186 */     gbc.gridwidth = 1;
/* 215:    */     
/* 216:188 */     gbc.anchor = 17;
/* 217:189 */     gbc.gridy = 1;
/* 218:190 */     gbc.gridx = 1;
/* 219:191 */     add(patientInfo, gbc);
/* 220:192 */     gbc.gridy = 2;
/* 221:193 */     add(therapyInfo, gbc);
/* 222:194 */     gbc.gridx = 2;
/* 223:195 */     gbc.gridy = 1;
/* 224:196 */     gbc.gridheight = 2;
/* 225:197 */     add(graphInfo, gbc);
/* 226:    */   }
/* 227:    */   
/* 228:    */   public void initializeInterface()
/* 229:    */   {
/* 230:201 */     double[][] testResults = (double[][])null;
/* 231:    */     
/* 232:    */ 
/* 233:    */ 
/* 234:205 */     this.thePatient.setAge(50);
/* 235:206 */     this.thePatient.setComorbidity(2);
/* 236:207 */     this.thePatient.setERStatus(2);
/* 237:208 */     this.thePatient.setTumorGrade(2);
/* 238:209 */     this.thePatient.setTumorSize(3);
/* 239:210 */     this.thePatient.setPositiveNodes(1);
/* 240:211 */     this.thePatient.calculateRisk();
/* 241:212 */     updateHormoneEfficacy(false);
/* 242:213 */     updateChemoEfficacy(false);
/* 243:214 */     updateCombinedEfficacy(false);
/* 244:215 */     this.thePatient.calculateResults();
/* 245:216 */     testResults = this.thePatient.getResults();
/* 246:217 */     if (testResults[0][0] != 49.399999999999999D) {
/* 247:217 */       this.consistencyCheck = true;
/* 248:    */     }
/* 249:218 */     if (testResults[0][1] != 0.0D) {
/* 250:218 */       this.consistencyCheck = true;
/* 251:    */     }
/* 252:219 */     if (testResults[0][2] != 47.299999999999997D) {
/* 253:219 */       this.consistencyCheck = true;
/* 254:    */     }
/* 255:220 */     if (testResults[0][3] != 3.3D) {
/* 256:220 */       this.consistencyCheck = true;
/* 257:    */     }
/* 258:221 */     if (testResults[1][1] != 0.0D) {
/* 259:221 */       this.consistencyCheck = true;
/* 260:    */     }
/* 261:222 */     if (testResults[2][1] != 7.8D) {
/* 262:222 */       this.consistencyCheck = true;
/* 263:    */     }
/* 264:223 */     if (testResults[3][1] != 7.8D) {
/* 265:223 */       this.consistencyCheck = true;
/* 266:    */     }
/* 267:224 */     if (this.consistencyCheck)
/* 268:    */     {
/* 269:225 */       this.consistencyString = new String(this.thePatient.getHormoneEffect() + ":" + this.thePatient.getChemoEffect() + ":" + this.thePatient.getCombinedEffect() + ":" + testResults[0][0] + ":" + testResults[0][1] + ":" + testResults[0][2] + ":" + testResults[0][3] + ":" + testResults[1][1] + ":" + testResults[2][1] + ":" + testResults[3][1]);
/* 270:226 */       return;
/* 271:    */     }
/* 272:229 */     this.thePatient = new BreastPatient();
/* 273:230 */     this.ageField.setValue(this.thePatient.getAge());
/* 274:231 */     this.comorbidityList.select(this.thePatient.getComorbidity());
/* 275:232 */     this.erStatusList.select(this.thePatient.getERStatus());
/* 276:233 */     this.tumorGradeList.select(this.thePatient.getTumorGrade());
/* 277:234 */     this.tumorSizeList.select(this.thePatient.getTumorSize());
/* 278:235 */     this.positiveNodeList.select(this.thePatient.getPositiveNodes());
/* 279:236 */     this.calculateForList.select(0);
/* 280:237 */     this.riskField.setValue(this.thePatient.getRisk());
/* 281:238 */     this.hormField.setValue(this.thePatient.getHormoneEffect());
/* 282:239 */     this.chemField.setValue(this.thePatient.getChemoEffect());
/* 283:240 */     this.combField.setValue(this.thePatient.getCombinedEffect());
/* 284:241 */     this.thePatient.calculateResults();
/* 285:242 */     this.graph.setResults(this.thePatient.getResults(), this.thePatient.getRelapse());
/* 286:    */   }
/* 287:    */   
/* 288:    */   public void initializeListeners()
/* 289:    */   {
/* 290:246 */     this.tumorGradeList.addItemListener(this);
/* 291:247 */     this.comorbidityList.addItemListener(this);
/* 292:248 */     this.erStatusList.addItemListener(this);
/* 293:249 */     this.tumorSizeList.addItemListener(this);
/* 294:250 */     this.positiveNodeList.addItemListener(this);
/* 295:251 */     this.calculateForList.addItemListener(this);
/* 296:252 */     this.setList.addItemListener(this);
/* 297:253 */     this.setList2.addItemListener(this);
/* 298:254 */     this.ageField.addTextListener(this);
/* 299:255 */     this.riskField.addTextListener(this);
/* 300:256 */     this.hormField.addTextListener(this);
/* 301:257 */     this.chemField.addTextListener(this);
/* 302:258 */     this.combField.addTextListener(this);
/* 303:259 */     this.printButton.addActionListener(this);
/* 304:260 */     this.helpButton.addActionListener(this);
/* 305:261 */     this.picsButton.addActionListener(this);
/* 306:262 */     this.progButton.addActionListener(this);
/* 307:    */   }
/* 308:    */   
/* 309:    */   public void initializeFonts()
/* 310:    */   {
/* 311:266 */     Font appFont = new Font("Serif", 0, 12);
/* 312:267 */     setFont(appFont);
/* 313:268 */     this.comorbidityList.setFont(appFont);
/* 314:269 */     this.erStatusList.setFont(appFont);
/* 315:270 */     this.tumorGradeList.setFont(appFont);
/* 316:271 */     this.tumorSizeList.setFont(appFont);
/* 317:272 */     this.positiveNodeList.setFont(appFont);
/* 318:273 */     this.calculateForList.setFont(appFont);
/* 319:274 */     this.setList.setFont(appFont);
/* 320:275 */     this.setList2.setFont(appFont);
/* 321:276 */     this.printButton.setFont(appFont);
/* 322:277 */     this.helpButton.setFont(appFont);
/* 323:278 */     this.progButton.setFont(appFont);
/* 324:279 */     this.riskLabel.setForeground(Color.blue);
/* 325:280 */     this.hormoLabel.setForeground(Color.blue);
/* 326:281 */     this.chemoLabel.setForeground(Color.blue);
/* 327:282 */     this.comboLabel.setForeground(Color.blue);
/* 328:283 */     this.patientLabel.setFont(new Font("Serif", 1, 14));
/* 329:284 */     this.therapyLabel.setFont(new Font("Serif", 1, 14));
/* 330:    */   }
/* 331:    */   
/* 332:    */   public void actionPerformed(ActionEvent ae)
/* 333:    */   {
/* 334:288 */     if (ae.getSource() == this.printButton)
/* 335:    */     {
/* 336:289 */       PrintDialog pdlg = new PrintDialog(getFrame(), this.thePatient.getRelapse());
/* 337:290 */       if (pdlg.continuePrinting()) {
/* 338:291 */         doServletPrint(pdlg);
/* 339:    */       }
/* 340:    */     }
/* 341:293 */     else if (ae.getSource() == this.helpButton)
/* 342:    */     {
/* 343:    */       try
/* 344:    */       {
/* 345:295 */         this.owner.getAppletContext().showDocument(new URL("http://www.adjuvantonline.com/breasthelp0306/breastindex.html"), "_blank");
/* 346:    */       }
/* 347:    */       catch (Exception localException) {}
/* 348:    */     }
/* 349:299 */     else if (ae.getSource() == this.picsButton)
/* 350:    */     {
/* 351:    */       try
/* 352:    */       {
/* 353:301 */         this.owner.getAppletContext().showDocument(new URL("http://www.adjuvantonline.com/breastimages/PicIndexMaster.htm"), "_blank");
/* 354:    */       }
/* 355:    */       catch (Exception localException1) {}
/* 356:    */     }
/* 357:305 */     else if (ae.getSource() == this.progButton)
/* 358:    */     {
/* 359:306 */       int newRisk = PrognosticDialog.execute(getFrame(), this.thePatient.getRisk(), "10 Year Risk Based on Size and Nodes:");
/* 360:307 */       this.thePatient.setRisk(newRisk);
/* 361:308 */       this.riskField.setValue(newRisk);
/* 362:309 */       updateGraph();
/* 363:    */     }
/* 364:    */   }
/* 365:    */   
/* 366:    */   public void itemStateChanged(ItemEvent ie)
/* 367:    */   {
/* 368:314 */     if (ie.getSource() == this.tumorGradeList)
/* 369:    */     {
/* 370:315 */       this.thePatient.setTumorGrade(this.tumorGradeList.getSelectedIndex());
/* 371:316 */       updateRisk();
/* 372:317 */       updateGraph();
/* 373:    */     }
/* 374:319 */     else if (ie.getSource() == this.comorbidityList)
/* 375:    */     {
/* 376:320 */       this.thePatient.setComorbidity(this.comorbidityList.getSelectedIndex());
/* 377:321 */       updateGraph();
/* 378:    */     }
/* 379:323 */     else if (ie.getSource() == this.erStatusList)
/* 380:    */     {
/* 381:324 */       this.thePatient.setERStatus(this.erStatusList.getSelectedIndex());
/* 382:325 */       updateRisk();
/* 383:326 */       updateHormoneEfficacy(false);
/* 384:327 */       updateChemoEfficacy(false);
/* 385:328 */       updateCombinedEfficacy(false);
/* 386:329 */       updateGraph();
/* 387:    */     }
/* 388:331 */     else if (ie.getSource() == this.tumorSizeList)
/* 389:    */     {
/* 390:332 */       this.thePatient.setTumorSize(this.tumorSizeList.getSelectedIndex());
/* 391:333 */       updateRisk();
/* 392:334 */       updateGraph();
/* 393:    */     }
/* 394:336 */     else if (ie.getSource() == this.positiveNodeList)
/* 395:    */     {
/* 396:337 */       this.thePatient.setPositiveNodes(this.positiveNodeList.getSelectedIndex());
/* 397:338 */       updateRisk();
/* 398:339 */       updateGraph();
/* 399:    */     }
/* 400:340 */     else if (ie.getSource() == this.calculateForList)
/* 401:    */     {
/* 402:341 */       if (this.calculateForList.getSelectedIndex() == 0) {
/* 403:342 */         this.thePatient.setRelapse(false);
/* 404:    */       } else {
/* 405:344 */         this.thePatient.setRelapse(true);
/* 406:    */       }
/* 407:346 */       updateRisk();
/* 408:347 */       updateHormoneEfficacy(false);
/* 409:348 */       updateChemoEfficacy(false);
/* 410:349 */       updateCombinedEfficacy(false);
/* 411:350 */       updateGraph();
/* 412:    */     }
/* 413:351 */     else if (ie.getSource() == this.setList)
/* 414:    */     {
/* 415:352 */       MessageDialog msgDlg = null;
/* 416:353 */       Panel pnl = null;
/* 417:354 */       switch (this.setList.getSelectedIndex())
/* 418:    */       {
/* 419:    */       case 1: 
/* 420:356 */         pnl = new Panel(new GridLayout(20, 1));
/* 421:357 */         pnl.add(new Label("Although the Overview suggests that adjuvant anthracycline"));
/* 422:358 */         pnl.add(new Label("based regimens are more efficacious than non-anthracycline"));
/* 423:359 */         pnl.add(new Label("based regimens, this is not universally true. For example, the"));
/* 424:360 */         pnl.add(new Label("short 12 week CA * 4 regimen appears equal to CMF."));
/* 425:361 */         pnl.add(new Label(" "));
/* 426:362 */         pnl.add(new Label("G1 or 1st Generation regimens have CMF like efficacy. CA * 4"));
/* 427:363 */         pnl.add(new Label("is such a regimen despite including an anthracycline."));
/* 428:364 */         pnl.add(new Label(" "));
/* 429:365 */         pnl.add(new Label("G2 or 2rd Generation regimens are superior to G1 regimens"));
/* 430:366 */         pnl.add(new Label("reducing the hazard of death or recurrence by an additional"));
/* 431:367 */         pnl.add(new Label("relative 15-20%. These regimens generally use >4 cycles of "));
/* 432:368 */         pnl.add(new Label("therapy and >2 agents, one of which is an anthracycline."));
/* 433:369 */         pnl.add(new Label(" "));
/* 434:370 */         pnl.add(new Label("Choosing this option projects a 16% proportional improvement"));
/* 435:371 */         pnl.add(new Label("relative to CMF like regimens in the risk of relapse and breast"));
/* 436:372 */         pnl.add(new Label("cancer related death. This estimate is derived from the September"));
/* 437:373 */         pnl.add(new Label("2000 Overview presentations.  As noted above this estimate may"));
/* 438:374 */         pnl.add(new Label("not be relevant to all anthracycline-based regimens."));
/* 439:375 */         pnl.add(new Label(" "));
/* 440:376 */         pnl.add(new Label("See the online help efficacy section for additional discussion."));
/* 441:377 */         msgDlg = new MessageDialog(getFrame(), "About Anthracycline Use", true, pnl);
/* 442:378 */         break;
/* 443:    */       case 2: 
/* 444:    */       case 3: 
/* 445:380 */         pnl = new Panel(new GridLayout(20, 1));
/* 446:381 */         pnl.add(new Label("The first widely used polychemotherapy for the adjuvant"));
/* 447:382 */         pnl.add(new Label("therapy of breast cancer was CMF. Adjuvant! classifies CMF"));
/* 448:383 */         pnl.add(new Label("as a 1st generation regimen."));
/* 449:384 */         pnl.add(new Label(" "));
/* 450:385 */         pnl.add(new Label("G1 or 1st Generation regimens have been, in Phase 3 studies,"));
/* 451:386 */         pnl.add(new Label("shown to be equal to CMF or to be better than no therapy to a"));
/* 452:387 */         pnl.add(new Label("degree similar to that expected for CMF. Examples of such"));
/* 453:388 */         pnl.add(new Label("regimens are CA*4 and FE(50)C*6"));
/* 454:389 */         pnl.add(new Label(" "));
/* 455:390 */         pnl.add(new Label("G2 or 2rd Generation regimens are superior to G1 regimens"));
/* 456:391 */         pnl.add(new Label("reducing the hazard of death or recurrence by an additional"));
/* 457:392 */         pnl.add(new Label("relative 15-20%."));
/* 458:393 */         pnl.add(new Label(" "));
/* 459:394 */         pnl.add(new Label("You have selected 1st generation regimen. Estimates of the"));
/* 460:395 */         pnl.add(new Label("efficacy of these regimens is derived from the Overview and"));
/* 461:396 */         pnl.add(new Label("are affected by age and in some instances ER status"));
/* 462:397 */         pnl.add(new Label(" "));
/* 463:398 */         pnl.add(new Label("See the online help efficacy section for additional discussion."));
/* 464:399 */         msgDlg = new MessageDialog(getFrame(), "About first generation regimens", true, pnl);
/* 465:400 */         break;
/* 466:    */       case 4: 
/* 467:    */       case 5: 
/* 468:402 */         pnl = new Panel(new GridLayout(16, 1));
/* 469:403 */         pnl.add(new Label("Adjuvant! stratifies adjuvant chemotherapy regimens by efficacy relative"));
/* 470:404 */         pnl.add(new Label("to CMF (the prototypic 1st Generation or G1 regimen)."));
/* 471:405 */         pnl.add(new Label(" "));
/* 472:406 */         pnl.add(new Label("As defined on the basis of Phase 3 clinical trials, 2nd generation regimens"));
/* 473:407 */         pnl.add(new Label("(G2) are superior to G1 regimens, reducing the hasard of death or recurrence"));
/* 474:408 */         pnl.add(new Label("by an additional relative 15-20%."));
/* 475:409 */         pnl.add(new Label(" "));
/* 476:410 */         pnl.add(new Label("You have selected 2nd generation regimen. A number of complex anthracycline"));
/* 477:411 */         pnl.add(new Label("regimens are of this general class which include CAF*6, FEC*6, FE(100)C*6, "));
/* 478:412 */         pnl.add(new Label("FAC*6, and CA*4 followed by T* 4. CD*4 is also such a regimen. Some of"));
/* 479:413 */         pnl.add(new Label("these regimens have only beentested/approved in the adjuvant therapy of node"));
/* 480:414 */         pnl.add(new Label("positive patients although, in theory, they should work as well in node"));
/* 481:415 */         pnl.add(new Label("negative patients."));
/* 482:416 */         pnl.add(new Label(" "));
/* 483:417 */         pnl.add(new Label("See the online help efficacy section for a detailed discussion of these."));
/* 484:418 */         pnl.add(new Label("and other regimens that may be of this class, and additional information."));
/* 485:419 */         msgDlg = new MessageDialog(getFrame(), "About second generation regimens", true, pnl);
/* 486:420 */         break;
/* 487:    */       case 6: 
/* 488:422 */         pnl = new Panel(new GridLayout(18, 1));
/* 489:423 */         pnl.add(new Label("Adjuvant! stratifies adjuvant chemotherapy regimens by efficacy relative"));
/* 490:424 */         pnl.add(new Label("to CMF (the prototypic 1st Generation or G1 regimen)."));
/* 491:425 */         pnl.add(new Label(" "));
/* 492:426 */         pnl.add(new Label("As defined on the basis of Phase 3 clinical trials, 2nd generation regimens"));
/* 493:427 */         pnl.add(new Label("(G2) are superior to G1 regimens, reducing the hasard of death or recurrence"));
/* 494:428 */         pnl.add(new Label("by an additional relative 15-20%."));
/* 495:429 */         pnl.add(new Label(" "));
/* 496:430 */         pnl.add(new Label("You have selected CA * 4 followed by Taxol * 4 (every 3 weeks). This appears"));
/* 497:431 */         pnl.add(new Label("to be a 2nd Generation regimen. Some regimens that include a taxane appear "));
/* 498:432 */         pnl.add(new Label("to be 2nd generation regimens while others appear to be 3rd generation"));
/* 499:433 */         pnl.add(new Label("regimens. Because this regimen was approximately 20% proportionally better"));
/* 500:434 */         pnl.add(new Label("than CA * 4, it appears to be a 2nd generation regimen. This regimen has only"));
/* 501:435 */         pnl.add(new Label("been tested/approved in the adjuvant therapy of node positive patients"));
/* 502:436 */         pnl.add(new Label("although it should, in theory, work as well in node negative patients."));
/* 503:437 */         pnl.add(new Label(" "));
/* 504:438 */         pnl.add(new Label("See the online help efficacy section for additional discussion of this"));
/* 505:439 */         pnl.add(new Label("regimen, the controversy about whether it works as well in ER+ as ER-"));
/* 506:440 */         pnl.add(new Label("patients, and for additional information."));
/* 507:441 */         msgDlg = new MessageDialog(getFrame(), "About second generation taxane regimens", true, pnl);
/* 508:442 */         break;
/* 509:    */       case 7: 
/* 510:444 */         pnl = new Panel(new GridLayout(22, 1));
/* 511:445 */         pnl.add(new Label("Third generation regimens have been shown to be a relative 15-20%"));
/* 512:446 */         pnl.add(new Label("better than 2nd generation regimens, which in turn have been shown"));
/* 513:447 */         pnl.add(new Label("to be 15-20% better than 1st generation regimens. Thus, these"));
/* 514:448 */         pnl.add(new Label("regimens are about a relative 35% better than CMF. However, these"));
/* 515:449 */         pnl.add(new Label("efficacy estimates are complex and indirect."));
/* 516:450 */         pnl.add(new Label(" "));
/* 517:451 */         pnl.add(new Label("Third generation regimens include the TAC * 6, FE(100)C * 3 the D * 3,"));
/* 518:452 */         pnl.add(new Label("and dose-dense CA * 4 followed by T * 4 (all q2w) regimens. The FEC * 4"));
/* 519:453 */         pnl.add(new Label("then T*8 [q1w] regimen has reported risk reductions for relapse of a size"));
/* 520:454 */         pnl.add(new Label("that would suggest that it is also a third generation regimen, but at this"));
/* 521:455 */         pnl.add(new Label("time has not reported an improvement in OS that reaches statistical"));
/* 522:456 */         pnl.add(new Label("significance. See the help files efficacy section for a detailed discussion"));
/* 523:457 */         pnl.add(new Label("of these and other regimens that may be of this class."));
/* 524:458 */         pnl.add(new Label(" "));
/* 525:459 */         pnl.add(new Label("For some of the accelerated paclitaxel regimens the question has been "));
/* 526:460 */         pnl.add(new Label("raised of whether they are particularly beneficial in ER negative patients"));
/* 527:461 */         pnl.add(new Label("with less benefit in ER positive patients. The evidence from these"));
/* 528:462 */         pnl.add(new Label("exploratory analyses is mixed and statistically weak so whether these"));
/* 529:463 */         pnl.add(new Label("subset analyses should be taken into account is a matter of controversy"));
/* 530:464 */         pnl.add(new Label("and uncertainty"));
/* 531:465 */         pnl.add(new Label(" "));
/* 532:466 */         pnl.add(new Label("See additional information in the online help."));
/* 533:467 */         msgDlg = new MessageDialog(getFrame(), "About third generation regimens", true, pnl);
/* 534:    */       }
/* 535:470 */       updateChemoEfficacy(false);
/* 536:471 */       updateCombinedEfficacy(false);
/* 537:472 */       updateGraph();
/* 538:    */     }
/* 539:473 */     else if (ie.getSource() == this.setList2)
/* 540:    */     {
/* 541:474 */       MessageDialog msgDlg = null;
/* 542:475 */       Panel pnl = null;
/* 543:476 */       switch (this.setList2.getSelectedIndex())
/* 544:    */       {
/* 545:    */       case 1: 
/* 546:478 */         pnl = new Panel(new GridLayout(28, 1));
/* 547:479 */         pnl.add(new Label("Aromatase inhibitors should only be used in women who are postmenopausal,"));
/* 548:480 */         pnl.add(new Label("and whose tumors are ER or PgR positive. They are probably ineffective in"));
/* 549:481 */         pnl.add(new Label("premenopausal women."));
/* 550:482 */         pnl.add(new Label(" "));
/* 551:483 */         pnl.add(new Label("The ASCO guidelines reccomend the inclusion of an aromatase inhibitor"));
/* 552:484 */         pnl.add(new Label("in the adjuvant hormonal therapy of postmenopausal ER-positive patients"));
/* 553:485 */         pnl.add(new Label("considering hormonal therapy. ASCO did not specify whether such"));
/* 554:486 */         pnl.add(new Label("adjuvant AI therapy should be as initial therapy instead of tamoxifen"));
/* 555:487 */         pnl.add(new Label("or after an initial 2-3 or 5 years of tamoxifen. There are no completed"));
/* 556:488 */         pnl.add(new Label("trials directly comparing these strategies. Whether any of these"));
/* 557:489 */         pnl.add(new Label("specific AI strategies is superior to the others at 10 years of follow-up"));
/* 558:490 */         pnl.add(new Label("is unclear. Strategies in which an aromatase inhibitor is given first, such"));
/* 559:491 */         pnl.add(new Label("as anastrozole in ATAC or letrozole in FEMTA, have the attractive feature of"));
/* 560:492 */         pnl.add(new Label("an immediate early advantage in reduction in relapse."));
/* 561:493 */         pnl.add(new Label(" "));
/* 562:494 */         pnl.add(new Label("The ATAC trial is the most mature trial comparing initial therapy with 5 years"));
/* 563:495 */         pnl.add(new Label("with 5 years of tamoxifen. The ATAC trial reported (at 68 months of median"));
/* 564:496 */         pnl.add(new Label("follow-up) a statistically significant 26% proportional risk reduction in the"));
/* 565:497 */         pnl.add(new Label("risk of relapse favoring anastrozole over tamoxifen. A similar reduction in"));
/* 566:498 */         pnl.add(new Label("the FEMTA study, which compares in two of its study arms 5 years of tamoxifen"));
/* 567:499 */         pnl.add(new Label("with 5 years of letrozole. An estimate of a 26% reduction in the risk of"));
/* 568:500 */         pnl.add(new Label("relapse compared to tamoxifen is used by Adjuvant! for the additional benefit"));
/* 569:501 */         pnl.add(new Label("for an initial AI. Because a statistically significant advantage in breast"));
/* 570:502 */         pnl.add(new Label("cancer specific or overall survival has not yet been shown in the ATAC or"));
/* 571:503 */         pnl.add(new Label("FEMTA trials for use of initial aromatase inhibitors over tamoxifen,"));
/* 572:504 */         pnl.add(new Label("such an advantage has not yet been projected by Adjuvant!"));
/* 573:505 */         pnl.add(new Label(" "));
/* 574:506 */         pnl.add(new Label("Additional information can be found in the online help."));
/* 575:507 */         msgDlg = new MessageDialog(getFrame(), "About initiating adjuvant hormonal therapy with an AI", true, pnl);
/* 576:508 */         break;
/* 577:    */       case 2: 
/* 578:510 */         pnl = new Panel(new GridLayout(29, 1));
/* 579:511 */         pnl.add(new Label("Aromatase inhibitors should only be used in women who are postmenopausal,"));
/* 580:512 */         pnl.add(new Label("and whose tumors are ER or PgR positive. They are probably ineffective in"));
/* 581:513 */         pnl.add(new Label("premenopausal women."));
/* 582:514 */         pnl.add(new Label(" "));
/* 583:515 */         pnl.add(new Label("The ASCO guidelines reccomend the inclusion of an aromatase inhibitor"));
/* 584:516 */         pnl.add(new Label("in the adjuvant hormonal therapy of postmenopausal ER-positive patients"));
/* 585:517 */         pnl.add(new Label("considering hormonal therapy. ASCO did not specify whether such"));
/* 586:518 */         pnl.add(new Label("adjuvant AI therapy should be as initial therapy instead of tamoxifen"));
/* 587:519 */         pnl.add(new Label("or after an initial 2-3 or 5 years of tamoxifen. There are no completed"));
/* 588:520 */         pnl.add(new Label("trials directly comparing these strategies. Whether any of these"));
/* 589:521 */         pnl.add(new Label("specific AI strategies is superior to the others at 10 years of follow-up"));
/* 590:522 */         pnl.add(new Label("is unclear."));
/* 591:523 */         pnl.add(new Label(" "));
/* 592:524 */         pnl.add(new Label("Strategies in which an aromatase inhibitor is given following tamoxifen"));
/* 593:525 */         pnl.add(new Label("have the theoretical advantage that a patient gets 2 different hormonal"));
/* 594:526 */         pnl.add(new Label("strategies, but this comes as the known disadvantage of an increased risk"));
/* 595:527 */         pnl.add(new Label("of recurrence during the initial tamoxifen treatment period (as compared"));
/* 596:528 */         pnl.add(new Label("to starting with an AI). Because of the large (but delayed) advantage "));
/* 597:529 */         pnl.add(new Label("of switching to an AI after 2-3 years of tamoxifen compared"));
/* 598:530 */         pnl.add(new Label("to continuing on tamoxifen of a proportional 30-40%, and to be consistent"));
/* 599:531 */         pnl.add(new Label("with the ASCO guidelines that do not favor pure AI strategies versus"));
/* 600:532 */         pnl.add(new Label("switching strategies, Adjuvant! shows the same amount of average benefit for"));
/* 601:533 */         pnl.add(new Label("an initial AI as a plan to start with tamoxifen for 2-3 years and to switch"));
/* 602:534 */         pnl.add(new Label("to an AI for 2-3 years when this benefit is viewed at 10 years of follow-up"));
/* 603:535 */         pnl.add(new Label("(an additional relative risk reduction of 26% compared to tamoxifen). Users"));
/* 604:536 */         pnl.add(new Label("may wish to also review the results of the ABCSG-8 trial."));
/* 605:537 */         pnl.add(new Label(" "));
/* 606:538 */         pnl.add(new Label("Clinical trial participation is encouraged."));
/* 607:539 */         pnl.add(new Label("Additional information can be found in the online help."));
/* 608:540 */         msgDlg = new MessageDialog(getFrame(), "Tamoxifen for 2-3 years followed by an AI for 2-3 years", true, pnl);
/* 609:541 */         break;
/* 610:    */       case 3: 
/* 611:543 */         pnl = new Panel(new GridLayout(14, 1));
/* 612:544 */         pnl.add(new Label("Ovarian ablation  should only be used in women who are in a "));
/* 613:545 */         pnl.add(new Label("premenopausal state, and whose tumors are ER or PgR positive."));
/* 614:546 */         pnl.add(new Label("There is no evidence for effectiveness in postmenopausal women."));
/* 615:547 */         pnl.add(new Label(" "));
/* 616:548 */         pnl.add(new Label("There is compelling evidence from North American and European"));
/* 617:549 */         pnl.add(new Label("studies for the effectiveness of ovarian ablation as a useful"));
/* 618:550 */         pnl.add(new Label("strategy for the adjuvant therapy of breast cancer.  Its effectiveness"));
/* 619:551 */         pnl.add(new Label("as compared to or in combination with tamoxifen remains an area"));
/* 620:552 */         pnl.add(new Label("of uncertainty and clinical trial research.  "));
/* 621:553 */         pnl.add(new Label(" "));
/* 622:554 */         pnl.add(new Label("Based on current clinical trial data,  Adjuvant! projects that ovarian"));
/* 623:555 */         pnl.add(new Label("ablation has approximately the same effectiveness as tamoxifen."));
/* 624:556 */         pnl.add(new Label(" "));
/* 625:557 */         pnl.add(new Label("See additional information in the online help."));
/* 626:558 */         msgDlg = new MessageDialog(getFrame(), "About Ovarian Ablation", true, pnl);
/* 627:559 */         break;
/* 628:    */       case 4: 
/* 629:561 */         pnl = new Panel(new GridLayout(16, 1));
/* 630:562 */         pnl.add(new Label("Ovarian ablation in combination with tamoxifen or an aromatase"));
/* 631:563 */         pnl.add(new Label("inhibitor should only be considered in women who are in a"));
/* 632:564 */         pnl.add(new Label("premenopausal state."));
/* 633:565 */         pnl.add(new Label(" "));
/* 634:566 */         pnl.add(new Label("Whether adding other hormonal theapies to ovarian ablation "));
/* 635:567 */         pnl.add(new Label("results in increased effectiveness is an area of controversy,"));
/* 636:568 */         pnl.add(new Label("uncertainty, and clinical trial research (the International SOFT"));
/* 637:569 */         pnl.add(new Label("and TEXT trials)."));
/* 638:570 */         pnl.add(new Label(" "));
/* 639:571 */         pnl.add(new Label("Adjuvant! projects that ovarian ablation combined with other"));
/* 640:572 */         pnl.add(new Label("hormonal theapy has approximately the same effectiveness as"));
/* 641:573 */         pnl.add(new Label("tamoxifen, although there are reasonable arguments that"));
/* 642:574 */         pnl.add(new Label("this is too conservative a view."));
/* 643:575 */         pnl.add(new Label(" "));
/* 644:576 */         pnl.add(new Label("Clinical trial participation is encouraged."));
/* 645:577 */         pnl.add(new Label("See additional information in the online help."));
/* 646:578 */         msgDlg = new MessageDialog(getFrame(), "About Tamoxifen + Ovarian Ablation", true, pnl);
/* 647:    */       }
/* 648:581 */       updateHormoneEfficacy(false);
/* 649:582 */       updateCombinedEfficacy(false);
/* 650:583 */       updateGraph();
/* 651:    */     }
/* 652:    */   }
/* 653:    */   
/* 654:    */   public void textValueChanged(TextEvent te)
/* 655:    */   {
/* 656:    */     try
/* 657:    */     {
/* 658:589 */       if (te.getSource() == this.ageField)
/* 659:    */       {
/* 660:590 */         this.thePatient.setAge(this.ageField.getValue());
/* 661:591 */         updateRisk();
/* 662:592 */         updateHormoneEfficacy(false);
/* 663:593 */         updateChemoEfficacy(false);
/* 664:594 */         updateCombinedEfficacy(false);
/* 665:595 */         updateGraph();
/* 666:596 */         if ((!this.shown35Warning) && (this.thePatient.getAge() < 35) && (this.thePatient.getAge() > 20))
/* 667:    */         {
/* 668:597 */           Panel pnl = new Panel(new GridLayout(7, 1));
/* 669:598 */           pnl.add(new Label("For women < 35 years old, particularly if ER positive,"));
/* 670:599 */           pnl.add(new Label("young age may confer addional risk of poor outcome."));
/* 671:600 */           pnl.add(new Label(" "));
/* 672:601 */           pnl.add(new Label("See additional information in the online help under"));
/* 673:602 */           pnl.add(new Label("the section \"Young Age (< 35 yrs)\". An adjustment"));
/* 674:603 */           pnl.add(new Label("(1.5 fold increase in risk) has been made by Adjuvant!"));
/* 675:604 */           pnl.add(new Label("to account for this."));
/* 676:605 */           MessageDialog msgDlg = new MessageDialog(getFrame(), "About Tamoxifen + Ovarian Ablation", true, pnl);
/* 677:606 */           this.shown35Warning = true;
/* 678:    */         }
/* 679:    */       }
/* 680:608 */       else if (te.getSource() == this.riskField)
/* 681:    */       {
/* 682:609 */         this.thePatient.setRisk(this.riskField.getValue());
/* 683:610 */         updateGraph();
/* 684:    */       }
/* 685:611 */       else if (te.getSource() == this.chemField)
/* 686:    */       {
/* 687:612 */         updateChemoEfficacy(true);
/* 688:613 */         updateGraph();
/* 689:    */       }
/* 690:614 */       else if (te.getSource() == this.hormField)
/* 691:    */       {
/* 692:615 */         updateHormoneEfficacy(true);
/* 693:616 */         updateGraph();
/* 694:    */       }
/* 695:617 */       else if (te.getSource() == this.combField)
/* 696:    */       {
/* 697:618 */         updateCombinedEfficacy(true);
/* 698:619 */         updateGraph();
/* 699:    */       }
/* 700:    */     }
/* 701:    */     catch (Exception localException) {}
/* 702:    */   }
/* 703:    */   
/* 704:    */   public void updateGraph()
/* 705:    */   {
/* 706:627 */     this.thePatient.calculateResults();
/* 707:628 */     this.graph.setResults(this.thePatient.getResults(), this.thePatient.getRelapse());
/* 708:    */   }
/* 709:    */   
/* 710:    */   public void updateRisk()
/* 711:    */   {
/* 712:632 */     this.thePatient.calculateRisk();
/* 713:633 */     this.riskField.setValue(this.thePatient.getRisk());
/* 714:    */   }
/* 715:    */   
/* 716:    */   public void updateHormoneEfficacy(boolean textUpdate)
/* 717:    */   {
/* 718:637 */     int textHormone = this.hormField.getValue();
/* 719:638 */     double horm = 0.0D;
/* 720:639 */     double hormRel = 0.0D;
/* 721:640 */     int indexCode = 0;
/* 722:642 */     if (textUpdate)
/* 723:    */     {
/* 724:643 */       this.thePatient.setHormoneEffect(textHormone);
/* 725:644 */       updateCombinedEfficacy(false);
/* 726:    */     }
/* 727:    */     else
/* 728:    */     {
/* 729:646 */       switch (this.thePatient.getERStatus())
/* 730:    */       {
/* 731:    */       case 0: 
/* 732:648 */         if (this.thePatient.getAge() < 50) {
/* 733:648 */           indexCode = 1;
/* 734:649 */         } else if (this.thePatient.getAge() < 60) {
/* 735:649 */           indexCode = 4;
/* 736:    */         } else {
/* 737:650 */           indexCode = 7;
/* 738:    */         }
/* 739:651 */         break;
/* 740:    */       case 1: 
/* 741:653 */         if (this.thePatient.getAge() < 50) {
/* 742:653 */           indexCode = 2;
/* 743:654 */         } else if (this.thePatient.getAge() < 60) {
/* 744:654 */           indexCode = 5;
/* 745:    */         } else {
/* 746:655 */           indexCode = 8;
/* 747:    */         }
/* 748:656 */         break;
/* 749:    */       case 2: 
/* 750:658 */         if (this.thePatient.getAge() < 50) {
/* 751:658 */           indexCode = 3;
/* 752:659 */         } else if (this.thePatient.getAge() < 60) {
/* 753:659 */           indexCode = 6;
/* 754:    */         } else {
/* 755:660 */           indexCode = 9;
/* 756:    */         }
/* 757:    */         break;
/* 758:    */       }
/* 759:664 */       switch (indexCode)
/* 760:    */       {
/* 761:    */       case 1: 
/* 762:665 */         horm = 20.0D;hormRel = 24.0D; break;
/* 763:    */       case 2: 
/* 764:666 */         horm = 32.0D;hormRel = 40.0D; break;
/* 765:    */       case 3: 
/* 766:667 */         horm = 0.0D;hormRel = 0.0D; break;
/* 767:    */       case 4: 
/* 768:668 */         horm = 21.0D;hormRel = 24.0D; break;
/* 769:    */       case 5: 
/* 770:669 */         horm = 32.0D;hormRel = 40.0D; break;
/* 771:    */       case 6: 
/* 772:670 */         horm = 0.0D;hormRel = 0.0D; break;
/* 773:    */       case 7: 
/* 774:671 */         horm = 23.0D;hormRel = 24.0D; break;
/* 775:    */       case 8: 
/* 776:672 */         horm = 32.0D;hormRel = 40.0D; break;
/* 777:    */       case 9: 
/* 778:673 */         horm = 0.0D;hormRel = 0.0D;
/* 779:    */       }
/* 780:675 */       switch (this.thePatient.getERStatus())
/* 781:    */       {
/* 782:    */       case 0: 
/* 783:677 */         if ((this.setList2.getSelectedIndex() == 1) || (this.setList2.getSelectedIndex() == 2)) {
/* 784:678 */           hormRel = 100.0D - (100.0D - hormRel) * 82.0D / 100.0D;
/* 785:    */         } else {
/* 786:679 */           hormRel = 100.0D - (100.0D - hormRel) * 100.0D / 100.0D;
/* 787:    */         }
/* 788:680 */         break;
/* 789:    */       case 1: 
/* 790:682 */         if ((this.setList2.getSelectedIndex() == 1) || (this.setList2.getSelectedIndex() == 2)) {
/* 791:683 */           hormRel = 100.0D - (100.0D - hormRel) * 74.0D / 100.0D;
/* 792:    */         } else {
/* 793:684 */           hormRel = 100.0D - (100.0D - hormRel) * 100.0D / 100.0D;
/* 794:    */         }
/* 795:685 */         break;
/* 796:    */       case 2: 
/* 797:687 */         hormRel = 0.0D;
/* 798:    */       }
/* 799:690 */       if (this.thePatient.getRelapse())
/* 800:    */       {
/* 801:691 */         this.thePatient.setHormoneEffect((int)Math.round(hormRel));
/* 802:692 */         if (textHormone != this.thePatient.getHormoneEffect()) {
/* 803:693 */           this.hormField.setValue((int)Math.round(hormRel));
/* 804:    */         }
/* 805:    */       }
/* 806:    */       else
/* 807:    */       {
/* 808:695 */         this.thePatient.setHormoneEffect((int)Math.round(horm));
/* 809:696 */         if (textHormone != this.thePatient.getHormoneEffect()) {
/* 810:697 */           this.hormField.setValue((int)Math.round(horm));
/* 811:    */         }
/* 812:    */       }
/* 813:    */     }
/* 814:    */   }
/* 815:    */   
/* 816:    */   public void updateChemoEfficacy(boolean textUpdate)
/* 817:    */   {
/* 818:705 */     int textChemo = this.chemField.getValue();
/* 819:706 */     double chem = 0.0D;
/* 820:707 */     double chemRel = 0.0D;
/* 821:708 */     int indexCode = 0;
/* 822:710 */     if (textUpdate)
/* 823:    */     {
/* 824:711 */       this.thePatient.setChemoEffect(textChemo);
/* 825:712 */       updateCombinedEfficacy(false);
/* 826:    */     }
/* 827:    */     else
/* 828:    */     {
/* 829:714 */       switch (this.thePatient.getERStatus())
/* 830:    */       {
/* 831:    */       case 0: 
/* 832:716 */         if (this.thePatient.getAge() < 50) {
/* 833:716 */           indexCode = 1;
/* 834:717 */         } else if (this.thePatient.getAge() < 60) {
/* 835:717 */           indexCode = 4;
/* 836:    */         } else {
/* 837:718 */           indexCode = 7;
/* 838:    */         }
/* 839:719 */         break;
/* 840:    */       case 1: 
/* 841:721 */         if (this.thePatient.getAge() < 50) {
/* 842:721 */           indexCode = 2;
/* 843:722 */         } else if (this.thePatient.getAge() < 60) {
/* 844:722 */           indexCode = 5;
/* 845:    */         } else {
/* 846:723 */           indexCode = 8;
/* 847:    */         }
/* 848:724 */         break;
/* 849:    */       case 2: 
/* 850:726 */         if (this.thePatient.getAge() < 50) {
/* 851:726 */           indexCode = 3;
/* 852:727 */         } else if (this.thePatient.getAge() < 60) {
/* 853:727 */           indexCode = 6;
/* 854:    */         } else {
/* 855:728 */           indexCode = 9;
/* 856:    */         }
/* 857:    */         break;
/* 858:    */       }
/* 859:731 */       switch (indexCode)
/* 860:    */       {
/* 861:    */       case 1: 
/* 862:732 */         chem = 30.0D;chemRel = 37.0D; break;
/* 863:    */       case 2: 
/* 864:733 */         chem = 30.0D;chemRel = 37.0D; break;
/* 865:    */       case 3: 
/* 866:734 */         chem = 30.0D;chemRel = 37.0D; break;
/* 867:    */       case 4: 
/* 868:735 */         chem = 18.0D;chemRel = 27.0D; break;
/* 869:    */       case 5: 
/* 870:736 */         chem = 16.0D;chemRel = 24.0D; break;
/* 871:    */       case 6: 
/* 872:737 */         chem = 22.0D;chemRel = 33.0D; break;
/* 873:    */       case 7: 
/* 874:738 */         chem = 10.0D;chemRel = 15.0D; break;
/* 875:    */       case 8: 
/* 876:739 */         chem = 8.0D;chemRel = 12.0D; break;
/* 877:    */       case 9: 
/* 878:740 */         chem = 15.0D;chemRel = 23.0D;
/* 879:    */       }
/* 880:742 */       switch (this.setList.getSelectedIndex())
/* 881:    */       {
/* 882:    */       case 1: 
/* 883:744 */         chem = 100.0D - (100.0D - chem) * 84.0D / 100.0D;
/* 884:745 */         chemRel = 100.0D - (100.0D - chemRel) * 84.0D / 100.0D;
/* 885:746 */         break;
/* 886:    */       case 2: 
/* 887:    */       case 3: 
/* 888:748 */         chem = 100.0D - (100.0D - chem) * 100.0D / 100.0D;
/* 889:749 */         chemRel = 100.0D - (100.0D - chemRel) * 100.0D / 100.0D;
/* 890:750 */         break;
/* 891:    */       case 4: 
/* 892:    */       case 5: 
/* 893:    */       case 6: 
/* 894:752 */         chem = 100.0D - (100.0D - chem) * 80.0D / 100.0D;
/* 895:753 */         chemRel = 100.0D - (100.0D - chemRel) * 80.0D / 100.0D;
/* 896:754 */         break;
/* 897:    */       case 7: 
/* 898:756 */         chem = 100.0D - (100.0D - chem) * 65.0D / 100.0D;
/* 899:757 */         chemRel = 100.0D - (100.0D - chemRel) * 65.0D / 100.0D;
/* 900:    */       }
/* 901:760 */       if (this.thePatient.getRelapse())
/* 902:    */       {
/* 903:761 */         this.thePatient.setChemoEffect((int)Math.round(chemRel));
/* 904:762 */         if (textChemo != this.thePatient.getChemoEffect()) {
/* 905:763 */           this.chemField.setValue((int)Math.round(chemRel));
/* 906:    */         }
/* 907:    */       }
/* 908:    */       else
/* 909:    */       {
/* 910:765 */         this.thePatient.setChemoEffect((int)Math.round(chem));
/* 911:766 */         if (textChemo != this.thePatient.getChemoEffect()) {
/* 912:767 */           this.chemField.setValue((int)Math.round(chem));
/* 913:    */         }
/* 914:    */       }
/* 915:    */     }
/* 916:    */   }
/* 917:    */   
/* 918:    */   public void updateCombinedEfficacy(boolean textUpdate)
/* 919:    */   {
/* 920:773 */     int textCombined = this.combField.getValue();
/* 921:774 */     double comb = 0.0D;
/* 922:777 */     if (textUpdate)
/* 923:    */     {
/* 924:778 */       this.thePatient.setCombinedEffect(textCombined);
/* 925:    */     }
/* 926:    */     else
/* 927:    */     {
/* 928:780 */       comb = 100.0D - (100.0D - this.thePatient.getChemoEffect()) * (100.0D - this.thePatient.getHormoneEffect()) / 100.0D;
/* 929:    */       
/* 930:782 */       this.thePatient.setCombinedEffect((int)Math.round(comb));
/* 931:783 */       if (textCombined != this.thePatient.getCombinedEffect()) {
/* 932:784 */         this.combField.setValue((int)Math.round(comb));
/* 933:    */       }
/* 934:    */     }
/* 935:    */   }
/* 936:    */   
/* 937:    */   public void doServletPrint(PrintDialog pdlg)
/* 938:    */   {
/* 939:    */     try
/* 940:    */     {
/* 941:790 */       double[][] myResults = this.thePatient.getResults();
/* 942:791 */       StringBuffer tmpString = new StringBuffer("https://www.adjuvantonline.com/servlet/BreastServlet2005?");
/* 943:792 */       tmpString.append("dis=" + pdlg.printDisclaimer() + "&");
/* 944:793 */       tmpString.append("all=" + pdlg.printAllTherapies() + "&");
/* 945:794 */       tmpString.append("lan=" + pdlg.printLanguage() + "&");
/* 946:795 */       tmpString.append("bw=" + pdlg.printBandW() + "&");
/* 947:796 */       tmpString.append("a=" + this.thePatient.getAge() + "&");
/* 948:797 */       tmpString.append("c=" + this.thePatient.getComorbidity() + "&");
/* 949:798 */       tmpString.append("e=" + this.thePatient.getERStatus() + "&");
/* 950:799 */       tmpString.append("g=" + this.thePatient.getTumorGrade() + "&");
/* 951:800 */       tmpString.append("t=" + this.thePatient.getTumorSize() + "&");
/* 952:801 */       tmpString.append("p=" + this.thePatient.getPositiveNodes() + "&");
/* 953:802 */       tmpString.append("r=" + this.thePatient.getRisk() + "&");
/* 954:803 */       tmpString.append("rel=" + this.thePatient.getRelapse() + "&");
/* 955:804 */       tmpString.append("meth=" + this.setList.getSelectedIndex() + "&");
/* 956:805 */       tmpString.append("meth2=" + this.setList2.getSelectedIndex() + "&");
/* 957:806 */       tmpString.append("e1=" + this.thePatient.getHormoneEffect() + "&");
/* 958:807 */       tmpString.append("e2=" + this.thePatient.getChemoEffect() + "&");
/* 959:808 */       tmpString.append("e3=" + this.thePatient.getCombinedEffect() + "&");
/* 960:809 */       tmpString.append("aa=" + myResults[0][0] + "&");
/* 961:810 */       tmpString.append("bb=" + myResults[0][1] + "&");
/* 962:811 */       tmpString.append("cc=" + myResults[0][2] + "&");
/* 963:812 */       tmpString.append("dd=" + myResults[0][3] + "&");
/* 964:813 */       tmpString.append("ee=" + myResults[1][0] + "&");
/* 965:814 */       tmpString.append("ff=" + myResults[1][1] + "&");
/* 966:815 */       tmpString.append("gg=" + myResults[1][2] + "&");
/* 967:816 */       tmpString.append("hh=" + myResults[1][3] + "&");
/* 968:817 */       tmpString.append("ii=" + myResults[2][0] + "&");
/* 969:818 */       tmpString.append("jj=" + myResults[2][1] + "&");
/* 970:819 */       tmpString.append("kk=" + myResults[2][2] + "&");
/* 971:820 */       tmpString.append("ll=" + myResults[2][3] + "&");
/* 972:821 */       tmpString.append("mm=" + myResults[3][0] + "&");
/* 973:822 */       tmpString.append("nn=" + myResults[3][1] + "&");
/* 974:823 */       tmpString.append("oo=" + myResults[3][2] + "&");
/* 975:824 */       tmpString.append("pp=" + myResults[3][3] + "&");
/* 976:825 */       if (this.email != null) {
/* 977:826 */         tmpString.append("email=" + this.email + "&");
/* 978:    */       }
/* 979:827 */       tmpString.append("v=7-17-03");
/* 980:828 */       System.out.println(tmpString.toString());
/* 981:829 */       ((Applet)getParent()).getAppletContext().showDocument(new URL(tmpString.toString()), "_blank");
/* 982:    */     }
/* 983:    */     catch (Exception e)
/* 984:    */     {
/* 985:831 */       MessageDialog tmpString = new MessageDialog(getFrame(), "Printing Error", true, new Label("The following error ocurred while printing:  " + e.getMessage()));
/* 986:    */     }
/* 987:    */   }
/* 988:    */   
/* 989:    */   private Frame getFrame()
/* 990:    */   {
/* 991:836 */     Container c = getParent();
/* 992:837 */     while ((c != null) && (!(c instanceof Frame))) {
/* 993:838 */       c = c.getParent();
/* 994:    */     }
/* 995:840 */     return (Frame)c;
/* 996:    */   }
/* 997:    */ }


/* Location:           C:\Users\mark\Dropbox\breastcancerapplet\BreastAppletV81.jar
 * Qualified Name:     BreastPanel
 * JD-Core Version:    0.7.0.1
 */